# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/jessie64"
  config.vm.hostname = "londonappdev3"

  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.synced_folder '../', '/vagrant', type: "nfs"
  config.vm.synced_folder 'salt', '/srv/salt'
  config.vm.synced_folder 'pillar', '/srv/pillar'

  config.vm.network "forwarded_port", guest: 80, host: 8081

  config.vm.provision :salt do |salt|
      salt.run_highstate = true
      salt.masterless = true
      salt.minion_config = "minion"
  end

end
